### PR TITLE
Fix https://github.com/glifio/safe/issues/151

### LINKED ISSUE #151: Landing page should show loading status if balances are loading for the first time
We see a quick flash of "0" before the balance loads, gets worse on poor internet connections

### PR DESCRIPTION
**Pull request by Schwartz10**
@navFooh this improves the UX around the home state while it's loading. It could still be improved by _not_ showing the loading indicator after the first render, but there wasn't a super quick fix (I could see) for implementing that - I tried some simple things, but there was a reoccurring weird side effect on the first render (for some reason the home page reverts state to the initial state when it renders?).

### CODE REVIEW

File: components/Home/index.tsx [hunk 1]
```diff
@@ -34,14 +35,18 @@ const VestingBox = styled(BalanceBox)`
...
+  const { AvailableBalance, Balance, loading } = useMsig()
   return (
     <>
       <BalanceBox>
         <h3>Available Balance</h3>
-        <span className='value'>
-          {makeFriendlyBalance(AvailableBalance, 6, true)}
-        </span>
+        {loading ? (
+          <LoadingIcon size='48px' />
```
Comment (navFooh) [inline components/Home/index.tsx:44]: The default size is `3em` which should be the same as `48px` here?

Comment (navFooh) [inline components/Home/index.tsx]: The default size is `3em` which should be the same as `48px` here?
Otherwise it's best to express in `em` as it scales with when the user changes their root font-size with the browser.

**Review by navFooh — CHANGES_REQUESTED** [review]
